Update yml

diff --git a/.github/workflows/cmake-multi-platform.yml b/.github/workflows/cmake-multi-platform.yml
--- a/.github/workflows/cmake-multi-platform.yml
+++ b/.github/workflows/cmake-multi-platform.yml
@@ -1,5 +1,3 @@
-# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
-# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
 name: CMake on multiple platforms
 
 on:
@@ -13,15 +11,7 @@ jobs:
     runs-on: ${{ matrix.os }}
 
     strategy:
-      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
       fail-fast: false
-
-      # Set up a matrix to run the following 3 configurations:
-      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
-      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
-      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
-      #
-      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
       matrix:
         os: [ubuntu-latest, windows-latest]
         build_type: [Release]
@@ -47,6 +37,7 @@ jobs:
     steps:
     - uses: actions/checkout@v4
 
+    # Ensure required dependencies for Poco
     - name: Install dependencies (Linux)
       if: runner.os == 'Linux'
       run: |
@@ -54,32 +45,40 @@ jobs:
         sudo apt-get install -y libssl-dev
 
     - name: Set reusable strings
-      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
       id: strings
       shell: bash
       run: |
         echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
-        echo "poco-cmake-dir=${{ github.workspace }}/Dependencies/CMAKE_BUILD/install/${{ matrix.build_type }}/lib/cmake/Poco" >> "$GITHUB_OUTPUT"
+        echo "poco-build-dir=${{ github.workspace }}/Dependencies/CMAKE_BUILD" >> "$GITHUB_OUTPUT"
+        echo "poco-install-dir=${{ github.workspace }}/Dependencies/CMAKE_BUILD/install/${{ matrix.build_type }}/lib/cmake/Poco" >> "$GITHUB_OUTPUT"
+
+    # Step to build Poco first before configuring the main project
+    - name: Build Poco
+      run: |
+        cmake -B ${{ steps.strings.outputs.poco-build-dir }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }}/Dependencies
+        cmake --build ${{ steps.strings.outputs.poco-build-dir }} --config ${{ matrix.build_type }} --target install
+
+    # Verify Poco built successfully
+    - name: Verify Poco Installation
+      run: |
+        echo "Checking Poco installation..."
+        ls -l ${{ steps.strings.outputs.poco-install-dir }} || echo "Poco not found!"
+        find ${{ steps.strings.outputs.poco-install-dir }} -name "PocoConfig.cmake" || echo "PocoConfig.cmake missing!"
 
     - name: Configure CMake
-      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
-      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
       run: >
         cmake -B ${{ steps.strings.outputs.build-output-dir }}
         -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
         -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
-        -DCMAKE_PREFIX_PATH=${{ steps.strings.outputs.poco-cmake-dir }}
-        -DPoco_DIR=${{ steps.strings.outputs.poco-cmake-dir }}
-        -DPocoFoundation_DIR=${{ steps.strings.outputs.poco-cmake-dir }}
+        -DCMAKE_PREFIX_PATH=${{ steps.strings.outputs.poco-install-dir }}
+        -DPoco_DIR=${{ steps.strings.outputs.poco-install-dir }}
+        -DPocoFoundation_DIR=${{ steps.strings.outputs.poco-install-dir }}
         -S ${{ github.workspace }}
 
     - name: Build
-      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
       run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
 
     - name: Test
       working-directory: ${{ steps.strings.outputs.build-output-dir }}
-      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
-      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
       run: ctest --build-config ${{ matrix.build_type }}
